# Generated by Django 5.0.1 on 2025-05-20 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('report_type', models.CharField(choices=[('student', 'Student Report'), ('faculty', 'Faculty Report'), ('attendance', 'Attendance Report'), ('examination', 'Examination Report'), ('fee', 'Fee Report'), ('library', 'Library Report'), ('hostel', 'Hostel Report'), ('custom', 'Custom Report')], max_length=20)),
                ('generation_date', models.DateTimeField(auto_now_add=True)),
                ('parameters', models.JSONField(default=dict)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('schedule_frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
