# Generated by Django 5.0.1 on 2025-05-23 19:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_data',
            field=models.TextField(blank=True, help_text='JSON or serialized data for the report', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.CreateModel(
            name='DatabaseBackup',
            fields=[
                ('backup_id', models.AutoField(primary_key=True, serialize=False)),
                ('backup_file', models.CharField(help_text='Path or identifier of the backup file', max_length=255)),
                ('backup_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('backup_size', models.IntegerField(default=0, help_text='Size in bytes')),
                ('is_automatic', models.BooleanField(default=True, help_text='Whether backup was created automatically or manually')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('in_progress', 'In Progress')], default='success', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Database Backup',
                'verbose_name_plural': 'Database Backups',
                'ordering': ['-backup_date'],
            },
        ),
    ]
