# Generated by Django 5.0.1 on 2025-05-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_report_report_data_report_report_file_databasebackup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='next_run',
        ),
        migrations.AlterField(
            model_name='report',
            name='is_scheduled',
            field=models.BooleanField(default=False, help_text='Whether this report runs on a schedule'),
        ),
        migrations.AlterField(
            model_name='report',
            name='last_run',
            field=models.DateTimeField(blank=True, help_text='When this report was last executed', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='report',
            name='schedule_frequency',
            field=models.CharField(blank=True, help_text='Frequency for scheduled reports (daily, weekly, monthly)', max_length=50, null=True),
        ),
    ]
